### ISSUE TITLE
Snap to scroll issue when changing orientation

### ISSUE THREAD

**Issue by felagund18** [chrisriesgo/xamarin-forms-carouselview#1]
![screenshots_2015-06-30-03-27-07](https://cloud.githubusercontent.com/assets/1384327/8415229/41d2bb20-1ed8-11e5-94de-73f326e90b0c.png)
Looking good at portrait mode

But, changing the orientation to landscape mode
![screenshots_2015-06-30-03-27-17](https://cloud.githubusercontent.com/assets/1384327/8415225/37628616-1ed8-11e5-8a26-da5e759b8224.png)

**Comment by biliktamas79** [comment]
You just have to refresh the width when the view was resized in the Droid project's CarouselLayoutRenderer:
protected override void OnSizeChanged(int w, int h, int oldw, int oldh)
        {
            // if the screen width changed
            if (_initialized && (w != oldw))
                // signal that on next Draw we will need ScrollView adjustment
                _initialized = false;
            base.OnSizeChanged(w, h, oldw, oldh);
        }

**Comment by felagund18** [comment]
thanks for the reply :)

**Comment by chrisriesgo** [comment]
Just pushed an update with the suggested fix :)
