### ISSUE TITLE
Xamarin.forms 2.2.0 update

### ISSUE THREAD

**Issue by bo-neis** [chrisriesgo/xamarin-forms-carouselview#22]
Hi,

Let me start by saying, great work.

Now to the sad part. I updated xamarin.forms from 1.4.4 to the new 2.2.0. And then the carousel is not working when I run it on android.
It stops during boot, with an "unexpected null" error. It happens when it goes into the android specific code, "Android.Widget.HorizontalScrollView.cs". In the ElementPropertyChanged. At "_scrollView = .....".

Have any one seen this issue. And if so do you have a solution?

Best regards
Bo

**Comment by chrisriesgo** [comment]
Thanks @boneisviel. There are a few outstanding issues in my examples. I'm unavailable the next few days, but I want to spend next week looking into each. Hopefully I can get you feedback by the end of the week :)

**Comment by bo-neis** [comment]
@chrisriesgo, thank you for you fast answer. Sounds perfect. Thank you.

**Comment by chrisriesgo** [comment]
@boneisviel - looks like this is a reflection issue. The private API inside of Xamarin.Forms changed, so the reflection code I have in place breaks. This is a great example why relying on reflection can be bad :-) 

I see a new `AHorizontalScrollView` type exposed, so I'll see if I can leverage that.

**Comment by bo-neis** [comment]
@chrisriesgo - that was fast. Thank you for have a look at it already. that sounds great.

**Comment by chrisriesgo** [comment]
From [my blog](http://chrisriesgo.com/xamarin-forms-carousel-view-recipe/#comment-2661573288), Afzal Ali found that this works:

``` csharp
GetField("_hScrollView",....)
```

**Comment by chrisriesgo** [comment]
@boneisviel ^^ check that out. See if that helps.

**Comment by bo-neis** [comment]
@chrisriesgo - I have tested it. And it works so far. Thank you Chris and Ali.
