### ISSUE TITLE
Slow swipe - System.InvalidOperationException: Sequence contains more than one element

### ISSUE THREAD

**Issue by hitinder** [chrisriesgo/xamarin-forms-carouselview#26]
When I do a slow swipe and release the slide in the middle with half of both the slides in screen, I get this error.

**Debug Log:**

07-19 13:45:17.860 I/dalvikvm( 6526): android.runtime.JavaProxyThrowable: System.InvalidOperationException: Sequence contains more than one element
07-19 13:45:17.860 I/dalvikvm( 6526):   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source) [0x0008e] in /Users/builder/data/lanes/3415/7db2aac3/source/mono/external/referencesource/System.Core/System/Linq/Enumerable.cs:1050 
07-19 13:45:17.860 I/dalvikvm( 6526):   at Xamarin.Forms.Platform.CarouselViewRenderer.<Initialize>b__8_2 () [0x00011] in <filename unknown>:0 
07-19 13:45:17.860 I/dalvikvm( 6526):   at Xamarin.Forms.Platform.CarouselViewRenderer+OnScrollListener.OnScrollStateChanged (Android.Support.V7.Widget.RecyclerView recyclerView, Int32 newState) [0x0003d] in <filename unknown>:0 
07-19 13:45:17.860 I/dalvikvm( 6526):   at Android.Support.V7.Widget.RecyclerView+OnScrollListener.n_OnScrollStateChanged_Landroid_support_v7_widget_RecyclerView_I (IntPtr jnienv, IntPtr native__this, IntPtr native_recyclerView, Int32 newState) [0x00011] in <filename unknown>:0 
07-19 13:45:17.860 I/dalvikvm( 6526):   at (wrapper dynamic-method) System.Object:fd7a9868-7ac5-48b1-8b65-4386ca0a009b (intptr,intptr,intptr,int)
07-19 13:45:17.860 I/dalvikvm( 6526):   at md532e00c7e41706cfac1bd1d309ed4a548.CarouselViewRenderer_OnScrollListener.n_onScrollStateChanged(Native Method)
07-19 13:45:17.860 I/dalvikvm( 6526):   at md532e00c7e41706cfac1bd1d309ed4a548.CarouselViewRenderer_OnScrollListener.onScrollStateChanged(CarouselViewRenderer_OnScrollListener.java:29)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:3990)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1219)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2508)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.View.dispatchTouchEvent(View.java:7728)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_dispatchTouchEvent(Native Method)
07-19 13:45:17.860 I/dalvikvm( 6526):   at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.dispatchTouchEvent(PlatformRenderer.java:55)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.860 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.860 I/dalvikvm( 6526):   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2165)
07-19 13:45:17.860 I/dalvikvm( 6526):   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1602)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.app.Activity.dispatchTouchEvent(Activity.java:2504)
07-19 13:45:17.870 I/dalvikvm( 6526):   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2113)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.View.dispatchPointerEvent(View.java:7908)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4132)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4011)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3568)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3618)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3587)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3694)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3595)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3751)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3568)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3618)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3587)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3595)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3568)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5780)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5760)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5731)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5869)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.os.MessageQueue.nativePollOnce(Native Method)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.os.MessageQueue.next(MessageQueue.java:138)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.os.Looper.loop(Looper.java:123)
07-19 13:45:17.870 I/dalvikvm( 6526):   at android.app.ActivityThread.main(ActivityThread.java:5290)
07-19 13:45:17.870 I/dalvikvm( 6526):   at java.lang.reflect.Method.invokeNative(Native Method)
07-19 13:45:17.870 I/dalvikvm( 6526):   at java.lang.reflect.Method.invoke(Method.java:515)
07-19 13:45:17.870 I/dalvikvm( 6526):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
07-19 13:45:17.870 I/dalvikvm( 6526):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
07-19 13:45:17.870 I/dalvikvm( 6526):   at dalvik.system.NativeStart.main(Native Method)
07-19 13:45:17.870 I/dalvikvm( 6526): "main" prio=5 tid=1 NATIVE
07-19 13:45:17.870 I/dalvikvm( 6526):   | group="main" sCount=0 dsCount=0 obj=0x41930d50 self=0x417b66c0
07-19 13:45:17.870 I/dalvikvm( 6526):   | sysTid=6526 nice=-1 sched=0/0 cgrp=apps handle=1074413908
07-19 13:45:17.870 I/dalvikvm( 6526):   | state=R schedstat=( 21980915458 1007283972 7182 ) utm=1932 stm=266 core=2
07-19 13:45:17.890 I/dalvikvm( 6526):   #00  pc 0000132e  /system/lib/libcorkscrew.so (unwind_backtrace_thread+29)
07-19 13:45:17.890 I/dalvikvm( 6526):   #01  pc 00061666  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const_, int)+33)
07-19 13:45:17.890 I/dalvikvm( 6526):   #02  pc 00055650  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const_, Thread_, bool)+395)
07-19 13:45:17.890 I/dalvikvm( 6526):   #03  pc 000556be  /system/lib/libdvm.so (dvmDumpThread(Thread_, bool)+25)
07-19 13:45:17.890 I/dalvikvm( 6526):   #04  pc 00039754  /system/lib/libdvm.so
07-19 13:45:17.890 I/dalvikvm( 6526):   #05  pc 0003d182  /system/lib/libdvm.so
07-19 13:45:17.890 I/dalvikvm( 6526):   at md532e00c7e41706cfac1bd1d309ed4a548.CarouselViewRenderer_OnScrollListener.n_onScrollStateChanged(Native Method)
07-19 13:45:17.890 I/dalvikvm( 6526):   at md532e00c7e41706cfac1bd1d309ed4a548.CarouselViewRenderer_OnScrollListener.onScrollStateChanged(CarouselViewRenderer_OnScrollListener.java:29)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:3990)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1219)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2508)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.View.dispatchTouchEvent(View.java:7728)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2212)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
In mgmain JNI_OnLoad
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_dispatchTouchEvent(Native Method)
07-19 13:45:17.890 I/dalvikvm( 6526):   at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.dispatchTouchEvent(PlatformRenderer.java:55)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
07-19 13:45:17.890 I/dalvikvm( 6526):   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2165)
07-19 13:45:17.890 I/dalvikvm( 6526):   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1602)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.app.Activity.dispatchTouchEvent(Activity.java:2504)
07-19 13:45:17.890 I/dalvikvm( 6526):   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2113)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.View.dispatchPointerEvent(View.java:7908)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4132)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4011)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3568)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3618)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3587)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3694)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3595)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3751)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3568)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3618)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3587)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3595)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3568)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5780)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5760)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5731)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5869)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.os.MessageQueue.nativePollOnce(Native Method)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.os.MessageQueue.next(MessageQueue.java:138)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.os.Looper.loop(Looper.java:123)
07-19 13:45:17.890 I/dalvikvm( 6526):   at android.app.ActivityThread.main(ActivityThread.java:5290)
07-19 13:45:17.890 I/dalvikvm( 6526):   at java.lang.reflect.Method.invokeNative(Native Method)
07-19 13:45:17.890 I/dalvikvm( 6526):   at java.lang.reflect.Method.invoke(Method.java:515)
07-19 13:45:17.890 I/dalvikvm( 6526):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:859)
07-19 13:45:17.890 I/dalvikvm( 6526):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:675)
07-19 13:45:17.890 I/dalvikvm( 6526):   at dalvik.system.NativeStart.main(Native Method)
07-19 13:45:17.890 I/dalvikvm( 6526): 
07-19 13:45:17.890 E/dalvikvm( 6526): VM aborting

**Comment by sdebruyn** [comment]
You're talking about a different CarouselView, the one in Xamarin.Forms prereleases.

**Comment by hitinder** [comment]
@SamuelDebruyn yes that's correct, is this not the same?

**Comment by sdebruyn** [comment]
No, this is a custom view made by @chrisriesgo which does about the same thing.

**Comment by hitinder** [comment]
@SamuelDebruyn Thanks for clearing out the confusion, can I report this issue to Xamarin, is there a repo for it? If you have a link, please forward. Other you can close this or I can. Thank you!
