### ISSUE TITLE
Major issue with scrolling in ListView

### ISSUE THREAD

**Issue by imgen** [chrisriesgo/xamarin-forms-carouselview#3]
Hi Chris, I am having a major issue that I am not able to fix by myself, could you help me?
The issue is that when I have a vertical ListView on one of the page, the ListView won't be able to scroll. I have to wrap a ScrollView around the ListView to be able to scroll. But it causes major performance issue if the ListView has a lot of items. Could you help me with this and provide a solution to fix the scrolling issue without resorting to wrapping a ScrollView around the ListView?

**Comment by chrisriesgo** [comment]
Hi @imgen. If I understand what you're attempting, nesting horizontal and vertical scrollviews/listviews is not supported by the Android framework.

Technically, it can be done by wrapping the listview in a scrollview, but that had other side effects (as it seems you're running into). I'm sorry. This doesn't help.

**Comment by imgen** [comment]
I actually fixed this issue by following this stackoverflow answer. Android doesn't solve this problem itself, but it provided ways to do so. 
http://stackoverflow.com/questions/6210895/listview-inside-scrollview-is-not-scrolling-on-android
Hope this can help someone
